import type { StabilityReloadIntent, StabilityReloadStatus } from './stability'

export interface Transaction {
  id: string
  date: string
  postedAt?: string
  description: string
  category: string
  ledgerCategory: string
  amount: number // Positive for inflow, negative for outflow
  /** Null is legacy unknown intent; zero is ordinary income; positive is applied reimbursement. */
  stabilityRecoveryTopUpAmount?: number | null
  stabilityReloadIntent?: StabilityReloadIntent
  /** Server-derived FIFO status for a Stability drawdown. */
  stabilityReloadStatus?: StabilityReloadStatus
  isPendingSync?: boolean
  /** Internal optimistic projection marker for a queue op that changes this row indirectly. */
  pendingSyncOperationId?: string
  // Set locally while a delete op for this record is still queued/in-flight in the outbox.
  isPendingDelete?: boolean
  // Set when this transaction was generated by confirming a recurring payment's bill.
  // Persists even after the originating RecurringPayment is deleted, so historical
  // cycles can still be identified as subscription payments.
  recurringPaymentId?: string | null
  recurringOccurrenceDate?: string | null
  // Set when this transaction was generated by purchasing a wishlist item.
  wishlistItemId?: number | null
  // Set when this transaction consumed a savings commitment. Deleting this row restores the
  // commitment while it is still the latest untouched completion.
  savingsGoalId?: number | null
  /** The account that receives this row's bucket leg. */
  accountId?: string | null
  /** Destination account for an in-bucket AccountMove row. */
  counterAccountId?: string | null
  /** Destination accounts per bucket for an Income split transaction. */
  splitAccountIds?: Record<string, string> | null
  /** Server-derived marker for structural rows that must not seed description autocomplete. */
  excludeFromAutocomplete?: boolean
  /** Server-derived marker for account balance/opening corrections, not real Stability movement. */
  isAccountBalanceAdjustment?: boolean
}

export type LedgerAccountKind = 'Bank' | 'EWallet' | 'Cash' | 'Card' | 'Other'

export interface LedgerAccount {
  id: string
  name: string
  bucket: 'Essentials' | 'Growth' | 'Stability' | 'Rewards'
  kind: LedgerAccountKind
  isArchived: boolean
  remaining: number
  createdAt: string
  updatedAt: string
  isPendingSync?: boolean
  pendingSyncOperationId?: string
  isPendingDelete?: boolean
}
