import type React from 'react'
import { cn } from '../../lib/utils'

/**
 * The brand mark's four ring segments -- the plan's buckets at 50 / 25 / 15 / 10 -- generated by
 * `scripts/brand-mark.mjs`, the single source for every icon, the favicon and the launch splash.
 */
const SEGMENTS = [
  'M51.83 29.08A21 21 0 0 1 55.44 70.28',
  'M51.83 70.92A21 21 0 0 1 29.72 55.44',
  'M29.08 51.83A21 21 0 0 1 34.64 35.68',
  'M37.36 33.23A21 21 0 0 1 48.17 29.08',
]

interface AppLogoProps {
  className?: string
  /**
   * Loading state: the segments light up one after another, like buckets filling. Static under
   * reduced motion (see `.brand-mark-animated` in index.css).
   */
  animated?: boolean
}

export const AppLogo: React.FC<AppLogoProps> = ({ className = 'size-9 rounded-xl', animated = false }) => (
  <span className={cn('inline-grid shrink-0 place-items-center overflow-hidden bg-brand', className)} aria-hidden="true">
    <svg viewBox="0 0 100 100" className={cn('size-full', animated && 'brand-mark-animated')} focusable="false">
      <g fill="none" stroke="currentColor" strokeWidth="12" className="text-brand-foreground">
        {SEGMENTS.map((d, index) => (
          <path key={d} d={d} style={{ '--segment': index } as React.CSSProperties} />
        ))}
      </g>
    </svg>
  </span>
)
